
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("User/new", "Create User")) ?>
</div>

<?php echo $this->tag->form(array("User/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search User</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="idUser">IdUser</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idUser", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="login">Login</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("login", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar">Avatar</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
