<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("User/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("User/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>IdUser</th>
            <th>Login</th>
            <th>Email</th>
            <th>Password</th>
            <th>Avatar</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $User) { ?>
        <tr>
            <td><?php echo $User->idUser ?></td>
            <td><?php echo $User->login ?></td>
            <td><?php echo $User->email ?></td>
            <td><?php echo $User->password ?></td>
            <td><?php echo $User->avatar ?></td>
            <td><?php echo $this->tag->linkTo(array("User/edit/" . $User->idUser, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("User/delete/" . $User->idUser, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("User/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("User/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("User/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("User/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
