-- MySQL Script generated by MySQL Workbench
-- 02/16/15 11:28:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema guta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guta` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `guta` ;

-- -----------------------------------------------------
-- Table `guta`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guta`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` CHAR(60) NULL,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guta`.`Sharedfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guta`.`Sharedfile` (
  `idShared_File` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_owner` INT NULL,
  `path` VARCHAR(45) NULL,
  PRIMARY KEY (`idShared_File`),
  INDEX `User_idx` (`id_user` ASC),
  INDEX `Owner_idx` (`id_owner` ASC),
  CONSTRAINT `User_File`
    FOREIGN KEY (`id_user`)
    REFERENCES `guta`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Owner`
    FOREIGN KEY (`id_owner`)
    REFERENCES `guta`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guta`.`Folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guta`.`Folder` (
  `idFolder` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`idFolder`),
  INDEX `User_idx` (`id_user` ASC),
  CONSTRAINT `User_Folder`
    FOREIGN KEY (`id_user`)
    REFERENCES `guta`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guta`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guta`.`Notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `message` TEXT NULL,
  `id_SharedFile` INT NULL,
  `unread` TINYINT(1) NULL,
  PRIMARY KEY (`idNotification`),
  INDEX `Shared_File_idx` (`id_SharedFile` ASC),
  CONSTRAINT `Sharedfile`
    FOREIGN KEY (`id_SharedFile`)
    REFERENCES `guta`.`Sharedfile` (`idShared_File`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
